-- Create SYNC_OPERATIONS_LOG table if it doesn't exist
CREATE TABLE IF NOT EXISTS SYNC_OPERATIONS_LOG (
    -- Primary Identifiers
    LOG_ID VARCHAR(50) PRIMARY KEY,
    SOURCE_FACILITY_ID VARCHAR(50),
    TARGET_ID VARCHAR(50),
    
    -- Operation Information
    OPERATION_TYPE VARCHAR(50),
    RECORD_COUNT INTEGER,
    LAG_SECONDS INTEGER,
    STATUS VARCHAR(50),
    
    -- Time Tracking
    SYNC_STARTED_AT TIMESTAMP_NTZ,
    SYNC_COMPLETED_AT TIMESTAMP_NTZ,
    DURATION_SECONDS INTEGER,
    
    -- Error Information
    ERROR_MESSAGE VARCHAR(1000)
);

-- Create OPERATION_STATISTICS table if it doesn't exist
CREATE TABLE IF NOT EXISTS OPERATION_STATISTICS (
    DATE_KEY DATE PRIMARY KEY,
    TOTAL_INSERTS INTEGER DEFAULT 0,
    TOTAL_UPDATES INTEGER DEFAULT 0,
    TOTAL_DELETES INTEGER DEFAULT 0,
    SUCCESSFUL_SYNCS INTEGER DEFAULT 0,
    FAILED_SYNCS INTEGER DEFAULT 0,
    AVG_LAG_SECONDS FLOAT DEFAULT 0,
    MAX_LAG_SECONDS INTEGER DEFAULT 0,
    TOTAL_RECORDS_PROCESSED INTEGER DEFAULT 0,
    LAST_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create SOURCE_FACILITIES table if it doesn't exist
CREATE TABLE IF NOT EXISTS SOURCE_FACILITIES (
    FACILITY_ID VARCHAR(50) PRIMARY KEY,
    FACILITY_NAME VARCHAR(100),
    FACILITY_TIMEZONE VARCHAR(50),
    FACILITY_LOCATION VARCHAR(200),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    LAST_SYNC_TIME TIMESTAMP_NTZ
);

-- Create SYNC_TARGETS table if it doesn't exist
CREATE TABLE IF NOT EXISTS SYNC_TARGETS (
    TARGET_ID VARCHAR(50) PRIMARY KEY,
    TARGET_NAME VARCHAR(100),
    TARGET_TYPE VARCHAR(50),
    CONNECTION_STRING VARCHAR(500),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    LAST_SYNC_TIME TIMESTAMP_NTZ
);

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_sync_log_operation_type ON SYNC_OPERATIONS_LOG(OPERATION_TYPE);
CREATE INDEX IF NOT EXISTS idx_sync_log_status ON SYNC_OPERATIONS_LOG(STATUS);
CREATE INDEX IF NOT EXISTS idx_sync_log_started_at ON SYNC_OPERATIONS_LOG(SYNC_STARTED_AT);
CREATE INDEX IF NOT EXISTS idx_source_facility_active ON SOURCE_FACILITIES(IS_ACTIVE);
CREATE INDEX IF NOT EXISTS idx_sync_target_active ON SYNC_TARGETS(IS_ACTIVE);

-- Sample data for SOURCE_FACILITIES
INSERT INTO SOURCE_FACILITIES (FACILITY_ID, FACILITY_NAME, FACILITY_TIMEZONE, FACILITY_LOCATION, IS_ACTIVE)
SELECT 'HOSP_001', 'Mumbai General Hospital', 'IST', 'Mumbai, India', TRUE
WHERE NOT EXISTS (SELECT 1 FROM SOURCE_FACILITIES WHERE FACILITY_ID = 'HOSP_001');

INSERT INTO SOURCE_FACILITIES (FACILITY_ID, FACILITY_NAME, FACILITY_TIMEZONE, FACILITY_LOCATION, IS_ACTIVE)
SELECT 'HOSP_002', 'New York Medical Center', 'EST', 'New York, USA', TRUE
WHERE NOT EXISTS (SELECT 1 FROM SOURCE_FACILITIES WHERE FACILITY_ID = 'HOSP_002');

INSERT INTO SOURCE_FACILITIES (FACILITY_ID, FACILITY_NAME, FACILITY_TIMEZONE, FACILITY_LOCATION, IS_ACTIVE)
SELECT 'HOSP_003', 'Paris Health Institute', 'CET', 'Paris, France', TRUE
WHERE NOT EXISTS (SELECT 1 FROM SOURCE_FACILITIES WHERE FACILITY_ID = 'HOSP_003');

-- Sample data for SYNC_TARGETS
INSERT INTO SYNC_TARGETS (TARGET_ID, TARGET_NAME, TARGET_TYPE, CONNECTION_STRING, IS_ACTIVE)
SELECT 'TGT_001', 'Central Database', 'SQL', 'jdbc:mysql://central-db:3306/medical_records', TRUE
WHERE NOT EXISTS (SELECT 1 FROM SYNC_TARGETS WHERE TARGET_ID = 'TGT_001');

INSERT INTO SYNC_TARGETS (TARGET_ID, TARGET_NAME, TARGET_TYPE, CONNECTION_STRING, IS_ACTIVE)
SELECT 'TGT_002', 'Analytics Platform', 'REST', 'https://analytics-api.example.com/ingest', TRUE
WHERE NOT EXISTS (SELECT 1 FROM SYNC_TARGETS WHERE TARGET_ID = 'TGT_002');

INSERT INTO SYNC_TARGETS (TARGET_ID, TARGET_NAME, TARGET_TYPE, CONNECTION_STRING, IS_ACTIVE)
SELECT 'TGT_003', 'Backup Storage', 'S3', 's3://medical-backup/treatments/', TRUE
WHERE NOT EXISTS (SELECT 1 FROM SYNC_TARGETS WHERE TARGET_ID = 'TGT_003');
